### ISSUE TITLE
The board has no color.

### ISSUE THREAD

**Issue by safarovd** [cs361fall2018/project-fortnitemasters#43]
Hey guys. I feel like the black and white layout doesn't work. Lets try to add some flare by coloring the board, background and Title? Thank you!

**Comment by safarovd** [comment]
I would also like to suggest that the marker colors are bland. I'll switch those! If anyone has suggestions feel free to edit. (Assign yourself a new issue)

**Comment by Garibaed** [comment]
Check out the colors I added in the pull request I made, let me know what works better!

**Comment by yuejOSU** [comment]
The colors are great, but I think I'm going to make a slight change in them for visual aspects for the user!

**Comment by yuejOSU** [comment]
Gotten it to work out, I will close this issue!
