### ISSUE TITLE
Center the boards.

### ISSUE THREAD

**Issue by safarovd** [cs361fall2018/project-fortnitemasters#47]
I was able to center the boards originally, but after my last commit they aren't centering. If you can help, please do

**Comment by yuejOSU** [comment]
Hey Dan, I submitted a comment on your pull request. If you don't get a chance to see that before you check this, I was thinking whether it might work to do instead of "position: relative", to do "position: fixed; top 50%, left 50%"? Let me know how that goes!

**Comment by safarovd** [comment]
Oh I haven't tried that yet! I hope it does because after adding the latest updates its alignment went off.

**Comment by yuejOSU** [comment]
Hey Dan, just checking up if the CSS code that I suggested helped? Let me know and we may be able to close this issue, as I haven't ran the most current update of the code yet.

**Comment by yuejOSU** [comment]
No problem! There were a couple issues when we implemented new features, but I got that straightened out for us!
