### ISSUE TITLE
Is there a way to flip the orientation of the boards

### ISSUE THREAD

**Issue by andytrinh** [cs361fall2018/project-fortnitemasters#49]
I think it's counterintuitive for the user's to be on the right side and the opponent's to be on the left.

**Comment by Garibaed** [comment]
Yes, I just had to mess with the css for a bit but I will submit a pull request for you to review.

**Comment by safarovd** [comment]
My bad. I just put them in side by side without thinking of which side is player and which isn't.

**Comment by safarovd** [comment]
Good job edgar!
