### ISSUE TITLE
Flexboxes

### ISSUE THREAD

**Issue by Garibaed** [cs361fall2018/project-fortnitemasters#53]

**Comment by Garibaed** [comment]
I don't remember if flexboxes are required to keep the containers in place for when the page is minimized. Is there anyone that knows how to fix this issue?

**Comment by yuejOSU** [comment]
I don't think that we should do flex boxes, at least not prioritize it over the other issues we have that makes our designs. If we have time before the assignment is due, perhaps we can implement such a feature?

**Comment by yuejOSU** [comment]
We will be omitting this as we don't need to fulfill it for a requirement.
