### ISSUE TITLE
Add a color-coded key to show users what colors means "miss" and what means "hit"

### ISSUE THREAD

**Issue by andytrinh** [cs361fall2018/project-fortnitemasters#56]

**Comment by yuejOSU** [comment]
I could try and do this, as well as slightly altering the colors for better visual appeal to the user. I'll update you on this issue if I make progress or need help!

**Comment by yuejOSU** [comment]
Yeah, for sure I'll take a look as soon as the code updates on my end!

**Comment by yuejOSU** [comment]
Color-coded the keys and aligned them into the box, closing issue.
