### ISSUE TITLE
Add the "sonar pulse"

### ISSUE THREAD

**Issue by andytrinh** [cs361fall2018/project-fortnitemasters#62]
"The sonar pulse allows a player to reveal a portion of the map, as shown in the figure below. The sonar pulse merely reveals the status of the cell as being free (shown as gray) or occupied (shown as black). It does not reveal the location of the ship's captain's quarters. A player can use a total of two (2) sonar pulses in a game, only after successfully sinking the first enemy ship."

**Comment by yuejOSU** [comment]
The back-end of sonar pulse is written, theoretically should work, but the attack doesn't work anymore so cannot test sonar pulse....

**Comment by yuejOSU** [comment]
I have narrowed down the issue to game.js, where the opponent's board is redrawn in redrawGrid(). If the two things for the opponent's board was commented out, we can attack but the sonar pulse does not work properly. I'm not sure how to fix that.

**Comment by yuejOSU** [comment]
Update: I did some debugging and those two lines still don't work, but I have slight functionality on the hovering of the sonar so that it shows the back-end works.

**Comment by safarovd** [comment]
Ok we've added the code for it. Now we need to work on the css aspect. This issue is closed.
