### ISSUE TITLE
Add "captains quarter" to all ship types

### ISSUE THREAD

**Issue by andytrinh** [cs361fall2018/project-fortnitemasters#63]
If the captains quarters is hit, then the ship is immediately sunk. The captains quarters for battleships and destroyers (but not minesweepers!) is armored, so it takes 2 attacks on the same square for it to "hit" (i.e. the result of the first attack always counts as a "miss").

This one looks like it'll take longer to implement so I'm thinking that two people can work on this feature.

**Comment by andytrinh** [comment]
I'm thinking we can add a private int named "shield" in the ship class to represent how much life the battleship and the destroyer have left and possibly adding if statements to determine whether or not to remove the ship.

Any ideas for how to automatically deleting the ship if the captain's quarters is hit?

**Comment by safarovd** [comment]
Good job Andy and Edgar. I see you guys have added the code for this. Would you consider the issue solved?
