### ISSUE TITLE
Create user stories for all features in sprint 3

### ISSUE THREAD

**Issue by andytrinh** [cs361fall2018/project-fortnitemasters#64]
Create user stories for the new features. The Battleships game will be a much more interesting game to play. Create a new wiki page on your team's repo called “Sprint 3 User Story”, and make sure that your user story adheres to the format:

Card: (“As a [user], I want [function], so that [value]”)
Conversation: (Details that clarify the user story)
Confirmation: (Tests to show when the User Story is completed)

INVEST guidelines: https://xp123.com/articles/invest-in-good-stories-and-smart-tasks/

**Comment by yuejOSU** [comment]
I have added the rest of the user stories for us and will close this issue.
